### ISSUE TITLE
Feature: anvils dropping on cobblestone create sand

### ISSUE THREAD

**Issue by YouHaveTrouble** [YouHaveTrouble/PurpurExtras#1]
TODO

**Comment by emielderckx** [comment]
O this was my suggestion. Yes this needs to be in the game xD. 

This was orginal made by Gnembon in: https://github.com/gnembon/carpet-extra 

Video thats shows it: https://www.youtube.com/watch?v=YMoqSneuevE
also a interesting video about almost the same thing: https://www.youtube.com/watch?v=nmqNDkjmJ7c

**Comment by YouHaveTrouble** [comment]
Implemented in [1.3](https://github.com/YouHaveTrouble/PurpurExtras/releases/tag/v1.3)

I don't think I'm gonna bother with multiple block one like in the last video tho.
