### ISSUE TITLE
[Feature Request] Add option to turn rabbits into killer rabbits

### ISSUE THREAD

**Issue by bluestormhunter** [YouHaveTrouble/PurpurExtras#11]
Add the possibility to turn rabbits into [killer bunnies](https://minecraft.fandom.com/wiki/Rabbit#:~:text=The%20Killer%20Bunny,-This%20feature%20is&text=It%20can%20be%20spawned%20only,reading%20%22The%20Killer%20Bunny%22.&text=damage%20on%20Normal%20difficulty.,to%20lunging%20at%20the%20player.) with the lightning-transforms-entities option.

**Comment by YouHaveTrouble** [comment]
Implemented in [v1.16.0](https://github.com/YouHaveTrouble/PurpurExtras/releases/tag/v1.16.0)
