### ISSUE TITLE
shears-shear-pumpkins breaks shears shearing beehives+sheep

### ISSUE THREAD

**Issue by GVNJPG** [YouHaveTrouble/PurpurExtras#3]
if shears-shear-pumpkins is set to true, automatic sheep and honeycomb farms no longer work. Setting shears-shear-pumpkins to false fixed the issue

**Comment by YouHaveTrouble** [comment]
Fixed in [1.10](https://github.com/YouHaveTrouble/PurpurExtras/releases/tag/v1.10)
