### ISSUE TITLE
Option gives-enchants-back not working

### ISSUE THREAD

**Issue by bluestormhunter** [YouHaveTrouble/PurpurExtras#5]
Setting the option grindstone: gives-enchants-back: to 'true' doesn't enable the feature. There is no error message in console. Can be observed on latest Purpur Build with vanilla client.

**Comment by YouHaveTrouble** [comment]
Do you have books in your inventory if in survival? :)

**Comment by bluestormhunter** [comment]
Yes. Tried with a single book and a stack of books. Grindstone gets used normal and returns XP

**Comment by YouHaveTrouble** [comment]
> Any Updates on this?
Not really, haven't had time to work on this plugin yet

**Comment by YouHaveTrouble** [comment]
I just tested this and it works as intended.
Please make sure you have books in your inventory while you take out the disenchant result.
Please also keep in mind that the feature does not remove curse enchantments.

**Comment by bluestormhunter** [comment]
I started setting up Permissions and removed /op rights from players. Maybe because of another plugin, maybe because of permissions but after that it just worked. 

Just some feedback in case anyone else comes across this.
