### ISSUE TITLE
Option respawn-anchor-needs-charges is toggled on when it should not be

### ISSUE THREAD

**Issue by bluestormhunter** [YouHaveTrouble/PurpurExtras#6]
Setting respawn-anchor-needs-charges: to 'true' makes players place fully charged respawn anchors. Although it would make sense, that if they need charges, they need to be charged first (obviously). Setting it to false places them normally again.

**Comment by YouHaveTrouble** [comment]
Fixed in [1.12](https://github.com/YouHaveTrouble/PurpurExtras/releases/tag/v1.12)
