### ISSUE TITLE
[Enhancement] More configurable Sleep message

### ISSUE THREAD

**Issue by unofficialreece** [YouHaveTrouble/PurpurExtras#9]
Is it possible for this plugin to be able to send sleep message though Bossbar, chat, or Title/subtitle?

**Comment by YouHaveTrouble** [comment]
I'm gonna need more information, what exactly do you mean by sleep message? The thing that displays "sleeping through the night"? or something else?

**Comment by unofficialreece** [comment]
> I'm gonna need more information, what exactly do you mean by sleep message? The thing that displays "sleeping through the night"? or something else?

Yes! But it send through different place, in bossbar, title, or chat with sound...

**Comment by YouHaveTrouble** [comment]
I believe that's not possible via plugin. Afaik plugin cannot modify/cancel the default sleep message
